# Generated by Django 4.2 on 2023-07-12 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueuedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(max_length=255, unique=True)),
                ('_func_name', models.CharField(max_length=255)),
                ('_status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('failed', 'failed'), ('completed', 'completed'), ('started', 'started'), ('finished', 'finished')], default='queued', max_length=255)),
                ('origin', models.CharField(help_text='The queue of the job', max_length=255)),
                ('enqueued_at', models.DateTimeField()),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('_kwargs', models.JSONField(blank=True, default=dict, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enqueued Job',
                'verbose_name_plural': 'Enqueued Jobs',
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='enqueuedjob',
            index=models.Index(fields=['job_id', 'origin'], name='job_handler_job_id_b512fa_idx'),
        ),
    ]
