# Generated by Django 4.2 on 2023-04-20 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('cookie', models.TextField(blank=True, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incoming Request',
                'verbose_name_plural': 'Incoming Requests',
                'ordering': ('-created',),
            },
        ),
    ]
