# Generated by Django 4.2 on 2023-04-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware_app', '0003_remove_requestlog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='body',
            field=models.BinaryField(blank=True, max_length=1073741824, null=True),
        ),
    ]
