# Generated by Django 4.2 on 2023-04-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('middleware_app', '0004_requestlog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='body',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='cookie',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='method',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='params',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='path',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='user',
        ),
    ]
