# Generated by Django 4.2 on 2023-04-20 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('middleware_app', '0005_remove_requestlog_body_remove_requestlog_cookie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='body',
            field=models.BinaryField(blank=True, max_length=1073741824, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='cookie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
