# Generated by Django 4.2 on 2023-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware_app', '0006_requestlog_body_requestlog_cookie_requestlog_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
