# Generated by Django 4.2 on 2023-07-14 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=1024)),
                ('token_expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Password Reset Token',
                'verbose_name_plural': 'User Password Reset Tokens',
                'ordering': ('-created', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserLoginOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(max_length=1024)),
                ('otp_expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login OTP',
                'verbose_name_plural': 'User Login OTPs',
                'ordering': ('-created', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='userpasswordresettoken',
            index=models.Index(fields=['id'], name='user_app_us_id_678499_idx'),
        ),
        migrations.AddIndex(
            model_name='userpasswordresettoken',
            index=models.Index(fields=['user'], name='user_app_us_user_id_bd48da_idx'),
        ),
        migrations.AddIndex(
            model_name='userpasswordresettoken',
            index=models.Index(fields=['token'], name='user_app_us_token_67fa09_idx'),
        ),
        migrations.AddIndex(
            model_name='userpasswordresettoken',
            index=models.Index(fields=['token_expires_at'], name='user_app_us_token_e_cb4dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginotp',
            index=models.Index(fields=['id'], name='user_app_us_id_a7d48c_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginotp',
            index=models.Index(fields=['user'], name='user_app_us_user_id_afc0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginotp',
            index=models.Index(fields=['otp'], name='user_app_us_otp_552bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginotp',
            index=models.Index(fields=['otp_expires_at'], name='user_app_us_otp_exp_f704de_idx'),
        ),
    ]
