# Generated by Django 4.2 on 2023-07-22 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userpasswordresettoken_userloginotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=1024)),
                ('alias', models.CharField(blank=True, max_length=64, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Token',
                'verbose_name_plural': 'User Tokens',
                'ordering': ('-created', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['id'], name='user_app_us_id_eb8ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user'], name='user_app_us_user_id_0bd533_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['token'], name='user_app_us_token_edeb74_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['alias'], name='user_app_us_alias_3f7eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['expires_at'], name='user_app_us_expires_52718d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertoken',
            unique_together={('user', 'token', 'alias')},
        ),
    ]
