# Generated by Django 4.2 on 2023-07-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_usertoken_usertoken_user_app_us_id_eb8ad9_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertoken',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='alias',
            field=models.CharField(default='proper', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usertoken',
            unique_together={('user', 'alias')},
        ),
    ]
