# Generated by Django 4.2 on 2023-07-24 19:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_usertoken_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.usertoken')),
            ],
            options={
                'verbose_name': 'User Token Usage',
                'verbose_name_plural': 'User Token Usages',
                'ordering': ('-created', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='usertokenusage',
            index=models.Index(fields=['id'], name='user_app_us_id_d57c67_idx'),
        ),
        migrations.AddIndex(
            model_name='usertokenusage',
            index=models.Index(fields=['token'], name='user_app_us_token_i_c80691_idx'),
        ),
        migrations.AddIndex(
            model_name='usertokenusage',
            index=models.Index(fields=['created'], name='user_app_us_created_86b9c1_idx'),
        ),
    ]
