# Generated by Django 4.2 on 2023-04-26 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('blurb', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'User Post',
                'verbose_name_plural': 'User Posts',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['id'], name='post_app_ta_id_361d41_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='post_app_ta_name_1c0cb4_idx'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='post_app.tag'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id'], name='post_app_po_id_72752e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='post_app_po_title_174dac_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='post_app_po_author__024389_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title', 'author'], name='post_app_po_title_168a53_idx'),
        ),
    ]
